# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false
r:
  - oldrel
  - release
  - devel

# Seems to be necessary with devtools 1.10.0, check again when the next version is on CRAN
r_github_packages:
  - hadley/testthat
  - jimhester/covr

after_success:
  - Rscript -e "covr::codecov(exclusions=c('src/sqlite3/sqlite3.c', 'src/sqlite3/extension-functions.c'))"

notifications:
  email:
    on_success: change
    on_failure: change

before_script:
- R -q -e 'install.packages("http://cran.r-project.org/src/contrib/Archive/Rcpp/Rcpp_0.12.7.tar.gz", repos = NULL)'
