# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

after_success:
- Rscript -e "covr::codecov(exclusions = c('src/sqlite3.c', 'src/extension-functions.c'))"

notifications:
  email:
    on_success: change
    on_failure: change
